# Generated by Django 3.1.2 on 2020-10-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='f_creado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
