# Generated by Django 3.1.2 on 2020-10-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_auto_20201005_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tareas',
            old_name='aignatura',
            new_name='asignatura',
        ),
    ]
