# Generated by Django 3.1.2 on 2020-10-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_auto_20201010_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='terminado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
