# Generated by Django 3.1.2 on 2020-10-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_auto_20201005_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='f_creado',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='f_entregado',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='f_final',
            field=models.DateField(blank=True),
        ),
    ]
