# Generated by Django 3.1.2 on 2020-10-10 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_auto_20201010_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
