# Generated by Django 3.1.2 on 2020-10-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_auto_20201005_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='f_entregado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='f_final',
            field=models.DateField(blank=True, null=True),
        ),
    ]
